version: '3.5'

services:
  app:
    image: dkr.hanaboso.net/hanaboso/go-base:1.13
    user: ${DEV_UID}:${DEV_GID}
    volumes:
      - ./:/app
      - ${GOPATH}/pkg:/go/pkg
      - ${DOCKER_SOCKET_PATH}:/var/run/docker.sock
    environment:
      DEV_UID: ${DEV_UID}
      DEV_GID: ${DEV_GID}
      RABBIT_DSN: amqp://guest:guest@rabbitmq:5672/

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - ${DEV_IP}:15672:15672
